-- Перенос товара, количества и цены из заголовка в позиции заказа.
-- Все изменения атомарны; повторный запуск ничего не меняет.
BEGIN;
DO $$
BEGIN
 IF to_regclass('public.order_items') IS NULL THEN
  CREATE TABLE order_items (
   order_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   order_id integer NOT NULL REFERENCES orders,
   line_no integer NOT NULL CHECK(line_no>0),
   product_id integer NOT NULL REFERENCES products,
   quantity integer NOT NULL CHECK(quantity>0),
   unit_price numeric(12,2) NOT NULL CHECK(unit_price>0),
   UNIQUE(order_id,line_no), UNIQUE(order_item_id,order_id)
  );
  INSERT INTO order_items(order_id,line_no,product_id,quantity,unit_price)
   SELECT order_id,1,product_id,quantity,unit_price FROM orders ORDER BY order_id;
  ALTER TABLE shipments ADD COLUMN order_item_id integer;
  UPDATE shipments s SET order_item_id=i.order_item_id FROM order_items i WHERE i.order_id=s.order_id;
  ALTER TABLE shipments ALTER COLUMN order_item_id SET NOT NULL;
  ALTER TABLE shipments ADD CONSTRAINT shipment_item_order_fk
   FOREIGN KEY(order_item_id,order_id) REFERENCES order_items(order_item_id,order_id);
  CREATE INDEX ON shipments(order_item_id,shipped_at);
  -- В пяти заказах добавляем вторую позицию. У 102 позиции используют общие компоненты.
  INSERT INTO order_items(order_id,line_no,product_id,quantity,unit_price) VALUES
   (101,2,7,2,1500),(102,2,1,1,12000),(104,2,3,1,6000),
   (108,2,12,3,2000),(111,2,1,1,12000);
  INSERT INTO shipments(shipment_id,order_id,shipped_at,quantity,order_item_id)
   SELECT 301,101,'2026-09-05',2,order_item_id FROM order_items WHERE order_id=101 AND line_no=2;
  INSERT INTO payments(payment_id,order_id,paid_at,amount,note)
   VALUES(301,101,'2026-09-05',3000,'Оплата дополнительной позиции');
  ALTER TABLE orders DROP COLUMN product_id, DROP COLUMN quantity, DROP COLUMN unit_price;
  GRANT SELECT ON order_items TO dashboard;
  COMMENT ON TABLE order_items IS 'Товар, количество и согласованная цена каждой позиции заказа.';
  COMMENT ON COLUMN shipments.order_item_id IS 'Отгрузка относится к конкретной позиции, а не к суммарному количеству заказа.';
 END IF;
END $$;
COMMIT;
